export const CHAT_START_PHOTO_UPLOADING = 'wisaw/chat/CHAT_START_PHOTO_UPLOADING'
export const CHAT_FINISH_PHOTO_UPLOADING = 'wisaw/chat/CHAT_FINISH_PHOTO_UPLOADING'

export const CHAT_UPDATE_PENDING_PHOTOS = 'wisaw/chat/CHAT_UPDATE_PENDING_PHOTOS'
