export const START_PHOTO_UPLOADING = 'wisaw/chat/START_PHOTO_UPLOADING'
export const FINISH_PHOTO_UPLOADING = 'wisaw/chat/FINISH_PHOTO_UPLOADING'

export const UPDATE_PENDING_PHOTOS = 'wisaw/chat/UPDATE_PENDING_PHOTOS'
