export const CHAT_START_PHOTO_UPLOADING = 'wisaw/chat/CHAT_START_PHOTO_UPLOADING'
export const CHAT_FINISH_PHOTO_UPLOADING = 'wisaw/chat/CHAT_FINISH_PHOTO_UPLOADING'
export const CHAT_UPDATE_PHOTO_UPLOADED = 'wisaw/chat/CHAT_UPDATE_PHOTO_UPLOADED'
